on:
  push:
    branches-ignore:    
      - master
      - main

jobs:
  mimics-scan:
    name: mimICS Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run mimICS
        uses: ykim-r7/test-action@main
        id: mimics
        with:
          api_key: ${{ secrets.ics_api_key }}
          base_url: ${{ secrets.ics_base_url }}
          config_name: AWS CIS Benchmark 1.4
          scan_name: Scan Me!
          target: example.yml
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scan_output.sarif
